use_frameworks!

target 'ADMobGenSDK_Example' do
  pod 'ADMobGenSDK', :path => '../'

  target 'ADMobGenSDK_Tests' do
    inherit! :search_paths

    
  end
  
#  pod 'ADMobGenMCAd'

  pod 'ADMobGenGDT','~> 4.10.19'
  pod 'ADMobileAd','~> 3.1.0'

  pod 'ADMobGenSDKWM','~> 2.5.1.5'

  

  pod 'MJRefresh', '~> 3.1.12'

end

pre_install do |installer|
  Pod::Installer::Xcode::TargetValidator.send(:define_method, :verify_no_static_framework_transitive_dependencies) {}
end
