use_frameworks!

target 'ADMobGenSDK_Example' do
  pod 'ADMobGenSDK', :path => '../'

  target 'ADMobGenSDK_Tests' do
    inherit! :search_paths

    
  end
  
#  pod 'ADMobGenMCAd'

#  pod 'ADMobGenGDT','4.10.5'
#  pod 'ADMobileAd','2.9.2'
#  pod 'ADMobGenSDK', '1.5.8'
#  pod 'ADMobGenMTG', '5.5.2'

#  pod 'ADMobGenMTG'

#  pod 'ADMobGenIFLY'

#  pod 'ADMobGenYD'

#  pod 'ADMobGenBaiDu'

#  pod 'ADMobGenSDKWM'

  

  pod 'MJRefresh', '~> 3.1.12'

end

pre_install do |installer|
  Pod::Installer::Xcode::TargetValidator.send(:define_method, :verify_no_static_framework_transitive_dependencies) {}
end
